name: Auto Version Increment

# DISABLED - Manual trigger only
# on:
#   push:
#     branches:
#       - main

on:
  workflow_dispatch:

jobs:
  increment-version:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Bump version to')"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
      
      - name: Increment version
        run: npm run version:update
      
      - name: Commit version changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package.json app/page.tsx
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No version changes to commit"
          else
            git commit -m "Bump version [auto]"
            git push
          fi
